# Generated by Django 4.0.5 on 2022-08-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('price_selling', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_score', models.CharField(blank=True, max_length=3, null=True)),
                ('seller_city', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'mdl_report',
            },
        ),
        migrations.CreateModel(
            name='ReportMerchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_merchant', models.CharField(blank=True, max_length=50, null=True)),
                ('other_merchant_score', models.CharField(blank=True, max_length=3, null=True)),
                ('other_merchant_city', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='proje.report')),
            ],
            options={
                'verbose_name': 'Report Merchant',
                'verbose_name_plural': 'Report Merchants',
                'db_table': 'mdl_reportMerchants',
            },
        ),
    ]
